# This is a basic workflow to help you get started with Actions

name: Fetch Latest Version (use carefully)

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: build
        run: |
          wget https://github.com/akariv/speculatron/archive/refs/heads/main.zip
          ln -s . speculatron-main
          unzip -o main.zip
          rm main.zip speculatron-main
          git status
          git checkout CONFIGURATION.ts package.json README.md
          git add .
          git reset .github
          git commit -m "Update to latest version"
          git push